using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace TabletHUD.Infrastructure
{
    public class AreaModel
    {
        public uint id;
        public string description;
        public string readable;
    }

    public class Area : Dictionary<int, AreaModel>
    {
        private void AddArea(uint id, string description, string readable)
        {
            AreaModel area = new AreaModel();
            area.id = id;
            area.description = description;
            area.readable = readable;

            base.Add(Convert.ToInt32(id), area);
        }

        public Area()
        {
            AddArea(0x0E3A6, "a1_c6_spidercave_01_entrance", "Caverns of Araneae");
            AddArea(0x132EC, "a1_c6_spidercave_01_main", "Caverns of Araneae");
            AddArea(0x0F506, "a1_c6_spidercave_01_queen", "Chamber of Queen Araneae");
            AddArea(0x36581, "a1_dun_crypt_dev_hell", "Development Hell");
            AddArea(0x38239, "a1_dun_qa_hell", "Quality Well");
            AddArea(0x1D455, "a1_fields_cave_swordofjustice_level01", "Khazra Den");
            AddArea(0x21045, "a1_fields_den", "Den of the Fallen Level 1");
            AddArea(0x2F6B8, "a1_fields_den_level02", "Den of the Fallen Level 2");
            AddArea(0x141C4, "a1_fields_randomdrlg_cavea_level01", "Lost Mine Level 1");
            AddArea(0x141C5, "a1_fields_randomdrlg_cavea_level02", "Lost Mine Level 2");
            AddArea(0x13D0D, "a1_fields_randomdrlg_scavengerdena_level01", "Scavenger's Den Level 1");
            AddArea(0x13D17, "a1_fields_randomdrlg_scavengerdena_level02", "Scavenger's Den Level 2");
            AddArea(0x2BC0C, "a1_fields_vendor_tinker_exterior", "Sheltered Cottage");
            AddArea(0x14286, "a1_highlands_randomdrlg_goatmancavea_level01", "Cave of the Moon Clan Level 1");
            AddArea(0x14287, "a1_highlands_randomdrlg_goatmancavea_level02", "Cave of the Moon Clan Level 2");
            AddArea(0x14196, "a1_highlands_randomdrlg_westtower_level01", "Watch Tower Level 1");
            AddArea(0x14197, "a1_highlands_randomdrlg_westtower_level02", "Watch Tower Level 2");
            AddArea(0x33A17, "a1_random_level01", "Whimsyshire");
            AddArea(0x144A6, "a1_trdun_blacksmith_cellar", "Cellar of the Damned");
            AddArea(0x16301, "a1_trdun_butcherslair_02", "Chamber of Suffering");
            AddArea(0x0ED2A, "a1_trdun_cain_intro", "Leoric's Passage");
            AddArea(0x21310, "a1_trdun_cave_highlands_random01_vendorrescue", "Highlands Cave");
            AddArea(0x0EBEC, "a1_trdun_cave_nephalem_01", "Warrior's Rest");
            AddArea(0x0EBED, "a1_trdun_cave_nephalem_02", "Crypt of the Ancients");
            AddArea(0x0EBEE, "a1_trdun_cave_nephalem_03", "Drowned Temple");
            AddArea(0x278AC, "a1_trdun_cave_old_ruins_random01", "The Cave Under the Well");
            AddArea(0x18FDA, "a1_trdun_crownroom", "Chancellor's Tomb");
            AddArea(0x138F4, "a1_trdun_crypt_event_tower_of_power", "The Lyceum");
            AddArea(0x18F9C, "a1_trdun_crypt_flooded_memories_level01", "Decaying Crypt Level 1");
            AddArea(0x287A6, "a1_trdun_crypt_flooded_memories_level02", "Decaying Crypt Level 2");
            AddArea(0x25BDC, "a1_trdun_crypt_special_00", "Defiled Crypt");
            AddArea(0x0ECB9, "a1_trdun_crypt_special_01", "Defiled Crypt Level 2");
            AddArea(0x2371E, "a1_trdun_event_jarofsouls", "Defiled Crypt");
            AddArea(0x14540, "a1_trdun_falsesecretpassage_01", "Defiled Crypt");
            AddArea(0x14541, "a1_trdun_falsesecretpassage_02", "Defiled Crypt");
            AddArea(0x14542, "a1_trdun_falsesecretpassage_03", "Defiled Crypt");
            AddArea(0x171D0, "a1_trdun_jail_level01", "The Cursed Hold");
            AddArea(0x1783D, "a1_trdun_jail_level01_cells", "The Cursed Hold");
            AddArea(0x04D3E, "a1_trdun_leoric01", "Halls of Agony Level 1");
            AddArea(0x04D3F, "a1_trdun_leoric02", "Halls of Agony Level 2");
            AddArea(0x04D40, "a1_trdun_leoric03", "Halls of Agony Level 3");
            AddArea(0x04D44, "a1_trdun_level01", "Cathedral Level 1");
            AddArea(0x04D47, "a1_trdun_level04", "Cathedral Level 2");
            AddArea(0x15763, "a1_trdun_level05_templar", "Cathedral Level 3");
            AddArea(0x04D49, "a1_trdun_level06", "Cathedral Level 4");
            AddArea(0x04D4B, "a1_trdun_level07b", "The Royal Crypts");
            AddArea(0x04D4D, "a1_trdun_level07d", "Crypt of the Skeleton King");
            AddArea(0x24447, "a1_trdun_tyraeljail", "Cells of the Condemned");
            AddArea(0x1CAA3, "a1_trdun_tyrael_level09", "Desolate Chamber");
            AddArea(0x04DD9, "a1_trout_adria'shut", "Adria's Hut");
            AddArea(0x0F5F8, "a1_trout_adriascellar", "The Hidden Cellar");
            AddArea(0x248A5, "a1_trout_batesfarmcellar", "Farmer's Cellar");
            AddArea(0x04DDD, "a1_trout_church", "Cathedral");
            AddArea(0x1A3B7, "a1_trout_fields_vendor_curios", "House of Curios");
            AddArea(0x2BE7B, "a1_trout_fields_vendor_curios_exterior", "Lonely Dwelling");
            AddArea(0x04DDF, "a1_trout_fishingvillage", "Wortham");
            AddArea(0x1FB03, "a1_trout_fishingvillageheights", "Wortham Bluffs");
            AddArea(0x20B72, "a1_trout_forlornfarm", "Forlorn Farm");
            AddArea(0x04DE2, "a1_trout_graveyard", "Cathedral Garden");
            AddArea(0x04DE4, "a1_trout_highlands", "Southern Highlands");
            AddArea(0x04DE5, "a1_trout_highlands2", "Northern Highlands");
            AddArea(0x004AF, "a1_trout_highlands3", "Leoric's Hunting Grounds");
            AddArea(0x16DC0, "a1_trout_highlands_bridge", "Highlands Crossing");
            AddArea(0x15718, "a1_trout_highlands_dunexterior_a", "Highlands Passage");
            AddArea(0x29CD1, "a1_trout_highlands_servanthouse_cellar_vendor", "Abandoned Servant House");
            AddArea(0x1F95F, "a1_trout_highlands_sub240_goatmangraveyard", "Ancient Pyre");
            AddArea(0x04DE7, "a1_trout_leoric'smanor", "Leoric's Manor Courtyard");
            AddArea(0x189F6, "a1_trout_leoric_manor_int", "Leoric's Manor");
            AddArea(0x20F08, "a1_trout_mysticwagon", "Karyna's Lost Wagon");
            AddArea(0x04DEB, "a1_trout_newtristram", "New Tristram");
            AddArea(0x26186, "a1_trout_newtristramoverlook", "Overlook Road");
            AddArea(0x316CE, "a1_trout_newtristram_attackarea", "New Tristram");
            AddArea(0x1A22B, "a1_trout_oldtristram_cellar", "Musty Cellar");
            AddArea(0x1A104, "a1_trout_oldtristram_cellar_1", "Dank Cellar");
            AddArea(0x1A105, "a1_trout_oldtristram_cellar_2", "Damp Cellar");
            AddArea(0x19322, "a1_trout_oldtristram_cellar_3", "Dark Cellar");
            AddArea(0x19C87, "a1_trout_oldtristram_treecave", "Mass Grave");
            AddArea(0x163FD, "a1_trout_old_tristram", "The Old Ruins");
            AddArea(0x164BC, "a1_trout_old_tristram_road", "Old Tristram Road");
            AddArea(0x18BE7, "a1_trout_old_tristram_road_cath", "Old Tristram Road");
            AddArea(0x35556, "a1_trout_scoundrel_event_old_mill_2", "The Old Mill");
            AddArea(0x1D43E, "a1_trout_townattack_chapelcellar", "Wortham Chapel Cellar");
            AddArea(0x04DF0, "a1_trout_tristramfields_a", "Fields of Misery");
            AddArea(0x04DF1, "a1_trout_tristramfields_b", "The Festering Woods");
            AddArea(0x0F085, "a1_trout_tristramfields_exita", "Drowned Temple");
            AddArea(0x2BD6F, "a1_trout_tristramfields_forsaken_grounds", "Forsaken Grounds");
            AddArea(0x2BD6E, "a1_trout_tristramfields_secluded_grove", "The Secluded Grove");
            AddArea(0x04DF2, "a1_trout_tristramwilderness", "The Weeping Hollow");
            AddArea(0x236AA, "a1_trout_tristramwilderness_subscenes", "The Weeping Hollow");
            AddArea(0x1FC73, "a1_trout_tristram_cainshouse", "Cain's House");
            AddArea(0x1AB91, "a1_trout_tristram_inn", "The Slaughtered Calf Inn");
            AddArea(0x15349, "a1_trout_tristram_leahsroom", "Leah's Room");
            AddArea(0x19821, "a1_trout_vendor_tinker_room", "Tinker's Hovel");
            AddArea(0x11C08, "a1_trout_wilderness_burialgrounds", "Cemetery of the Forsaken");
            AddArea(0x30ADF, "a1_trout_wilderness_corpsehouse", "Pillaged Home");
            AddArea(0x236A1, "a1_trout_wilderness_sub80_familytree", "The Rathe Family Plot");
            AddArea(0x2F0B6, "a2dun_aqd_oasis_level00", "Waterlogged Passage");
            AddArea(0x2F0B1, "a2dun_aqd_oasis_level01", "Hidden Aqueducts");
            AddArea(0x0ED55, "a2_belial_room_01", "Imperial Palace");
            AddArea(0x13D1A, "a2_belial_room_intro", "Imperial Palace");
            AddArea(0x04D4F, "a2_c1dun_swr_caldeum_01", "Sewers of Caldeum");
            AddArea(0x04D53, "a2_c2dun_zolt_treasurehunter", "Chamber of the Lost Idol");
            AddArea(0x0E069, "a2_c3dun_aqd_oasis_level01", "Hidden Channel");
            AddArea(0x04D52, "a2_cadun_zolt_timed01_level01", "The Crumbling Vault");
            AddArea(0x29108, "a2_cadun_zolt_timed01_level02", "Vault Treasure Room");
            AddArea(0x19234, "a2_caldeum", "City of Caldeum");
            AddArea(0x33613, "a2_caldeum_uprising", "City of Caldeum");
            AddArea(0x245A7, "a2_caout_alcarnus_randomcellar_1", "Alcarnus Cellar");
            AddArea(0x245A8, "a2_caout_alcarnus_randomcellar_2", "Sandy Cellar");
            AddArea(0x245A9, "a2_caout_alcarnus_randomcellar_3", "Town Cellar");
            AddArea(0x0D24A, "a2_caout_boneyard_01", "Desolate Sands");
            AddArea(0x0F8B2, "a2_caout_borderlandskhamsin", "Khasim Outpost");
            AddArea(0x0EE8A, "a2_caout_borderlands_khamsin_mine", "Command Post");
            AddArea(0x2FAC4, "a2_caout_cellar_alcarnus_main", "Lair of the Witch");
            AddArea(0x0D811, "a2_caout_ct_refugeecamp", "Caldeum Bazaar");
            AddArea(0x318FD, "a2_caout_ct_refugeecamp_gates", "Gates of Caldeum");
            AddArea(0x2917A, "a2_caout_ct_refugeecamp_hub", "Hidden Camp");
            AddArea(0x2AA00, "a2_caout_hub_inn", "Searing Sands Inn");
            AddArea(0x2D7BB, "a2_caout_interior_c_dogbite", "Blood Cellar");
            AddArea(0x232F5, "a2_caout_interior_h_rockworm", "Deserted Cellar");
            AddArea(0x04D81, "a2_caout_mine_abandoned_cellar", "Fuad's Cellar");
            AddArea(0x0E051, "a2_caout_oasis", "Dahlgur Oasis");
            AddArea(0x0E664, "a2_caout_oasis1_water", "Dahlgur Oasis");
            AddArea(0x0E058, "a2_caout_oasis2", "Desolate Sands");
            AddArea(0x1B100, "a2_caout_oasiscellars", "Ransacked Cellar");
            AddArea(0x2ACE2, "a2_caout_oasis_exit", "Ancient Path");
            AddArea(0x2AD07, "a2_caout_oasis_exit_a", "Path to the Oasis");
            AddArea(0x33BDD, "a2_caout_oasis_rakanishu", "Dahlgur Oasis");
            AddArea(0x27099, "a2_caout_oasis_randomcellar_1", "Storage Cellar");
            AddArea(0x2709A, "a2_caout_oasis_randomcellar_2", "Old Fisherman's Cellar");
            AddArea(0x2709B, "a2_caout_oasis_randomcellar_3", "Storm Cellar");
            AddArea(0x27BE7, "a2_caout_oasis_randomcellar_4", "Swampy Cellar");
            AddArea(0x04D7F, "a2_caout_stingingwinds", "Stinging Winds");
            AddArea(0x04D71, "a2_caout_stingingwinds_alcarnus_tier1", "Alcarnus");
            AddArea(0x04D72, "a2_caout_stingingwinds_alcarnus_tier2", "Alcarnus");
            AddArea(0x29886, "a2_caout_stingingwinds_bridge", "Black Canyon Bridge");
            AddArea(0x04D7C, "a2_caout_stingingwinds_canyon", "Sundered Canyon");
            AddArea(0x288EF, "a2_caout_stingingwinds_fallencamp01", "The Lost Caravan");
            AddArea(0x04D7E, "a2_caout_stingingwinds_postbridge", "Black Canyon Mines");
            AddArea(0x04D7B, "a2_caout_stingingwinds_prealcarnus", "Road to Alcarnus");
            AddArea(0x04D7D, "a2_caout_stingingwinds_prebridge", "Howling Plateau");
            AddArea(0x1DA4A, "a2_caout_stranded2", "Abandoned Mineworks");
            AddArea(0x1BEBB, "a2_caout_zakarwamerchantcellar", "Rotting Cellar");
            AddArea(0x26F64, "a2_cave_random01", "Sirocco Caverns Level 1");
            AddArea(0x35E85, "a2_cave_random01_level02", "Sirocco Caverns Level 2");
            AddArea(0x19218, "a2_cultistcellareast", "Secret Altar");
            AddArea(0x19214, "a2_cultistcellarwest", "Hidden Conclave");
            AddArea(0x0F9F3, "a2_dun_aqd_control_a", "Western Flow Control");
            AddArea(0x0F9F4, "a2_dun_aqd_control_b", "Eastern Flow Control");
            AddArea(0x26B82, "a2_dun_aqd_oasis_randomfacepuzzle_large", "Tomb of Khan Dakab");
            AddArea(0x26AB0, "a2_dun_aqd_oasis_randomfacepuzzle_small", "Tomb of Sardar");
            AddArea(0x0F520, "a2_dun_aqd_special_01", "Ancient Waterway");
            AddArea(0x0F53A, "a2_dun_aqd_special_a", "Western Channel");
            AddArea(0x0F53C, "a2_dun_aqd_special_b", "Eastern Channel");
            AddArea(0x23D96, "a2_dun_aqd_swr-to-oasis_level01", "Ruined Cistern");
            AddArea(0x31F55, "a2_dun_cave_bloodvial_01", "Cave of the Betrayer Level 1");
            AddArea(0x31F83, "a2_dun_cave_bloodvial_02", "Cave of the Betrayer Level 2");
            AddArea(0x29616, "a2_dun_oasis_cave_mapdungeon", "Mysterious Cave Level 1");
            AddArea(0x2F6BF, "a2_dun_oasis_cave_mapdungeon_level02", "Mysterious Cave Level 2");
            AddArea(0x1B37F, "a2_dun_portalroulette_a", "The Veiled Treasure");
            AddArea(0x0E47E, "a2_dun_swr_adria_level01", "The Wretched Pit");
            AddArea(0x1B205, "a2_dun_swr_caldeum_sewers_01", "Flooded Causeway");
            AddArea(0x1E12E, "a2_dun_zolt_blood02_level01_part1", "Vault of the Assassin");
            AddArea(0x25872, "a2_dun_zolt_blood02_level01_part2", "Vault of the Assassin");
            AddArea(0x0EB22, "a2_dun_zolt_bossfight_level04", "Soulstone Chamber");
            AddArea(0x0F0C0, "a2_dun_zolt_head_random01", "The Forgotten Ruins");
            AddArea(0x04D55, "a2_dun_zolt_level01", "The Unknown Depths");
            AddArea(0x04D56, "a2_dun_zolt_level02", "The Storm Halls");
            AddArea(0x04D57, "a2_dun_zolt_level03", "Halls of Dusk");
            AddArea(0x04D58, "a2_dun_zolt_lobby", "Archives of Zoltun Kulle");
            AddArea(0x2AFBA, "a2_dun_zolt_lobbycenter", "The Terminus");
            AddArea(0x04D59, "a2_dun_zolt_random_level01", "The Ruins Level 1");
            AddArea(0x36571, "a2_dun_zolt_random_level02", "The Ruins Level 2");
            AddArea(0x2FDCF, "a2_dun_zolt_random_portalroulette_02", "The Fowl Lair");
            AddArea(0x13AD0, "a2_dun_zolt_shadowrealm_level01", "Realm of Shadow");
            AddArea(0x2270B, "a2_event_dyingmanmine", "Hadi's Claim Mine");
            AddArea(0x2FD9E, "a2_event_priceofmercy_cellar", "Abandoned Cellar");
            AddArea(0x2FE81, "a2_rockworm_cellar_cave", "Tunnels of the Rockworm");
            AddArea(0x1B437, "a2_trdun_boneyard_spider_cave_01", "Vile Cavern Level 1");
            AddArea(0x35758, "a2_trdun_boneyard_spider_cave_02", "Vile Cavern Level 2");
            AddArea(0x1B433, "a2_trdun_boneyard_worm_cave_01", "Cave of Burrowing Horror Level 1");
            AddArea(0x35759, "a2_trdun_boneyard_worm_cave_02", "Cave of Burrowing Horror Level 2");
            AddArea(0x0F46F, "a2_trdun_cave_oasis_random01", "Ancient Cave Level 1");
            AddArea(0x2F6C2, "a2_trdun_cave_oasis_random01_level02", "Ancient Cave Level 2");
            AddArea(0x0F46E, "a2_trdun_cave_oasis_random02", "Flooded Cave Level 1");
            AddArea(0x27551, "a2_trdun_cave_oasis_random02_level02", "Flooded Cave Level 2");
            AddArea(0x3253E, "a3dun_hub_adriatower_intro_01", "Bastion's Keep Watchtower");
            AddArea(0x31222, "a3dun_hub_adria_tower", "Bastion's Keep Watchtower");
            AddArea(0x1B39C, "a3_azmodanfight", "Heart of Sin");
            AddArea(0x1B7A4, "a3_battlefield_a", "The Battlefields");
            AddArea(0x1B7B5, "a3_battlefield_b", "Fields of Slaughter");
            AddArea(0x1B7C4, "a3_battlefield_c", "Edge of the Abyss");
            AddArea(0x10F80, "a3_bridge_01", "Rakkis Crossing");
            AddArea(0x25DA8, "a3_bridge_choke_a", "The Bridge of Korsikk");
            AddArea(0x25C14, "a3_dun_battlefield_gate", "The Arreat Gate");
            AddArea(0x224AD, "a3_dun_bridge_interior_random01", "Bridge Stores");
            AddArea(0x32270, "a3_dun_bridge_interior_random02", "Bridge Stores");
            AddArea(0x15040, "a3_dun_crater_level_01", "Arreat Crater Level 1");
            AddArea(0x1D209, "a3_dun_crater_level_02", "Arreat Crater Level 2");
            AddArea(0x1D20A, "a3_dun_crater_level_03", "The Core of Arreat");
            AddArea(0x13B97, "a3_dun_crater_st_level01", "Tower of the Damned Level 1");
            AddArea(0x1D365, "a3_dun_crater_st_level01b", "Tower of the Cursed Level 1");
            AddArea(0x13B98, "a3_dun_crater_st_level02", "Tower of the Damned Level 2");
            AddArea(0x2200A, "a3_dun_crater_st_level02b", "Tower of the Cursed Level 2");
            AddArea(0x14CD2, "a3_dun_crater_st_level04", "Heart of the Damned");
            AddArea(0x1D368, "a3_dun_crater_st_level04b", "Heart of the Cursed");
            AddArea(0x2E3A1, "a3_dun_icecaves_random_01", "Caverns of Frost Level 1");
            AddArea(0x36206, "a3_dun_icecaves_random_01_level_02", "Caverns of Frost Level 2");
            AddArea(0x2EA66, "a3_dun_icecaves_timed_01", "Icefall Caves Level 1");
            AddArea(0x36207, "a3_dun_icecaves_timed_01_level_02", "Icefall Caves Level 2");
            AddArea(0x16B11, "a3_dun_keep_hub", "Bastion's Keep Stronghold");
            AddArea(0x2D38C, "a3_dun_keep_hub_inn", "The Armory");
            AddArea(0x126AC, "a3_dun_keep_level03", "The Keep Depths Level 1");
            AddArea(0x16BAF, "a3_dun_keep_level04", "The Keep Depths Level 2");
            AddArea(0x21500, "a3_dun_keep_level05", "The Keep Depths Level 3");
            AddArea(0x2AA4A, "a3_dun_keep_random_01", "Fortified Bunker Level 1");
            AddArea(0x36238, "a3_dun_keep_random_01_level_02", "Fortified Bunker Level 2");
            AddArea(0x2C7F2, "a3_dun_keep_random_02", "The Barracks Level 1");
            AddArea(0x36239, "a3_dun_keep_random_02_level_02", "The Barracks Level 2");
            AddArea(0x2C802, "a3_dun_keep_random_03", "Battlefield Stores Level 1");
            AddArea(0x3623A, "a3_dun_keep_random_03_level_02", "Battlefield Stores Level 2");
            AddArea(0x2C8E6, "a3_dun_keep_random_04", "The Foundry Level 1");
            AddArea(0x36241, "a3_dun_keep_random_04_level_02", "The Foundry Level 2");
            AddArea(0x35EE9, "a3_dun_keep_random_cellar_01", "Cryder's Outpost");
            AddArea(0x35EE8, "a3_dun_keep_random_cellar_02", "The Forward Barracks");
            AddArea(0x303F7, "a3_dun_keep_random_cellar_03", "The Underbridge");
            AddArea(0x3558F, "a3_dun_keep_thebreach_level04", "The Breach");
            AddArea(0x16B20, "a3_dun_rmpt_level01", "Skycrown Battlements");
            AddArea(0x16BF5, "a3_dun_rmpt_level02", "Stonefort");
            AddArea(0x1B280, "a3_gluttony_boss", "The Larder");
            AddArea(0x25845, "a4dun_diablo_shadowrealm_01", "Realm of Terror");
            AddArea(0x3227A, "a4dun_spire_diabloentrance", "The Pinnacle of Heaven");
            AddArea(0x34964, "a4dun_spire_exterior", "The Great Span");
            AddArea(0x1ABFB, "a4_dun_diablo_arena", "The Crystal Arch");
            AddArea(0x348C3, "a4_dun_diablo_arena_phase3", "The Crystal Arch");
            AddArea(0x1D44A, "a4_dun_garden3_spireentrance", "The Crystal Colonnade");
            AddArea(0x1ABCA, "a4_dun_garden_of_hope_01", "Gardens of Hope 1st Tier");
            AddArea(0x1ABCC, "a4_dun_garden_of_hope_02", "Gardens of Hope 2nd Tier");
            AddArea(0x1AA5D, "a4_dun_heaven_1000_monsters_fight", "The Vestibule of Light");
            AddArea(0x2F169, "a4_dun_heaven_1000_monsters_fight_entrance", "The Diamond Gates");
            AddArea(0x1ABD6, "a4_dun_hell_portal_01", "Hell Rift");
            AddArea(0x1ABDB, "a4_dun_hell_portal_02", "Hell Rift");
            AddArea(0x301ED, "a4_dun_keep_hub", "Bastion's Keep Stronghold");
            AddArea(0x23120, "a4_dun_libraryoffate", "Library of Fate");
            AddArea(0x307A4, "a4_dun_spire_00", "Gateway to the Silver Spire");
            AddArea(0x1ABE2, "a4_dun_spire_01", "The Silver Spire Level 1");
            AddArea(0x1ABE4, "a4_dun_spire_02", "The Silver Spire Level 2");
            AddArea(0x1ABE6, "a4_dun_spire_03", "The Silver Spire Level 4");
            AddArea(0x33728, "a4_dun_spire_04", "The Silver Spire Level 5");
            AddArea(0x313C4, "a4_dun_spire_sigilroom_a", "Blessed Chancel");
            AddArea(0x2AE7A, "a4_dun_spire_sigilroom_b", "Holy Sanctum");
            AddArea(0x313C6, "a4_dun_spire_sigilroom_c", "Radiant Chapel");
            AddArea(0x313C7, "a4_dun_spire_sigilroom_d", "Sacellum of Virtue");
            AddArea(0x04D60, "axe bad data", "");
            AddArea(0x41E24, "duelworld", "Scorched Chapel");
            AddArea(0x38705, "limbo", "");
            AddArea(0x04D9C, "pvparena", "Arena");
            AddArea(0x3BA58, "pvp_cald_swr_arena", "The Fetid Pools");
            AddArea(0x3BA59, "pvp_caout_arena", "Pit of the Condemned");
            AddArea(0x3BA5A, "pvp_keep_arena", "[temp] Bastion's Forge");
            AddArea(0x04DA2, "pvp_maze_01", "The Hedge Maze of Deadly Shrubbery");
            AddArea(0x3BA5B, "pvp_neph_arena", "Altar of Courage");
            AddArea(0x04DA3, "pvp_octogon_01", "The Octagon of Certain Doom");
            AddArea(0x04DA4, "pvp_pillar_01", "Carls Canadian Crazy Map");
            AddArea(0x04DA5, "pvp_stairs_01", "Raised Areas of Death!");
            AddArea(0x04DA6, "pvp_test_blueteam", "Khazra Encampment");
            AddArea(0x04DA7, "pvp_test_neutral", "Contested Grounds");
            AddArea(0x04DA8, "pvp_test_redteam", "Undead Cemetery");
            AddArea(0x3EAFE, "uber_bossworld1", "Realm of Discord");
            AddArea(0x3E850, "uber_bossworld2", "Realm of Chaos");
            AddArea(0x3EADE, "uber_bossworld3", "Realm of Turmoil");
            AddArea(0x3EC5B, "uber_portalworld", "Heretic's Abode");
        }
    }
}
